include("${CMAKE_CURRENT_LIST_DIR}/common_python_common_pre.cmake")

##
if (NOT DEFINED PROJECT_DOCKER_CONTAINER_NAME)
    set(PROJECT_DOCKER_CONTAINER_NAME "")
endif()
if (NOT DEFINED PROJECT_DOCKER_USER)
    set(PROJECT_DOCKER_USER "")
endif()
if (NOT DEFINED PROJECT_DOCKER_MAIN_APP_DIR)
    set(PROJECT_DOCKER_MAIN_APP_DIR "${PROJECT_SRC_DIR}")
endif()
